- name: Generate Workflow
  hosts: localhost
  vars:
    wf: "wf00"  # Set the value of wf variable
    env: "dev"  # Set the value of env variable
    wf_dir: "../workflows"
    swf_dir: "../subworkflows"
    dest_dir: "/tmp/{{ wf }}"
  tasks:
    - name: Load order and common files
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ wf_dir }}/{{ wf }}/order.yml"
        - "{{ wf_dir }}/{{ wf }}/common.yml"
        - "{{ wf_dir }}/{{ wf }}/env.{{ env }}.yml"
      register: loaded_files

    - name: Clean up destination directory
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: absent

    - name: Combine configuration
      set_fact:
        combined_config: "{{ loaded_files.results | map(attribute='ansible_facts') | list | combine }}"
      when: loaded_files.results | length > 0

    - name: Flatten lists in combined configuration
      set_fact:
        combined_config_flat: "{{ combined_config | combine({'modules_order': combined_config.modules_order | flatten}) }}"
      when: combined_config is defined

    # - name: Debug flattened combined configuration
    #   debug:
    #     var: combined_config_flat

    - name: Generate UUIDs for nodes
      set_fact:
        node_uuids: "{{ node_uuids | default([]) + [uuid] }}"
      loop: "{{ combined_config_flat.modules_order }}"
      vars:
        uuid: "{{ lookup('pipe', 'python3 -c \"import uuid; print(uuid.uuid4())\"') }}"

    - name: Add webhook node to start the workflow
      set_fact:
        nodes: "[{{ lookup('template', playbook_dir + '/templates/webhook.j2') | from_json }}]"
      vars:
        webhook_uuid: "{{ lookup('pipe', 'python3 -c \"import uuid; print(uuid.uuid4())\"') }}"

    - name: Generate nodes for main workflow template
      set_fact:
        nodes: "{{ nodes | default([]) + [{
          'parameters': {
            'source': 'localFile',
            'workflowPath': dest_dir + '/' + item + '/main.json',
            'options': {}
          },
          'name': 'Execute ' + item + ' Workflow',
          'type': 'n8n-nodes-base.executeWorkflow',
          'typeVersion': 1,
          'position': [660 + (index * 200), 340],
          'id': node_uuids[index]
        }] }}"
      loop: "{{ combined_config_flat.modules_order }}"
      loop_control:
        index_var: index

    # - name: Debug flattened combined configuration
    #   debug:
    #     var: nodes

    - name: Create connections between nodes
      set_fact:
        connections: >-
          {{
            connections | default({}) | combine({
              (nodes[index]['name']): {
                'main': [[{
                  'node': nodes[index + 1]['name'],
                  'type': 'main',
                  'index': 0
                }]]
              }
            })
          }}
      loop: "{{ range(0, nodes | length - 1) }}"
      loop_control:
        index_var: index

    - name: Set up variables for main workflow template
      set_fact:
        meta: "{{ {'meta': combined_config_flat.get('meta', {})} }}"
      when: combined_config_flat is defined

    - name: Create destination directory
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Copy subworkflows directory
      ansible.builtin.copy:
        src: "{{ swf_dir }}"
        dest: "{{ dest_dir }}"
        remote_src: yes
        force: yes

    - name: Generate main workflow template
      template:
        src: templates/workflow_template.j2
        dest: "{{ dest_dir }}/main_workflow_{{ wf }}.json"
      vars:
        meta: "{{ meta }}"
        nodes: "{{ nodes }}"
        connections: "{{ {'connections': connections} }}"
      when: combined_config_flat is defined
